package mx.saccsa.creditos

import grails.rest.RestfulController

import grails.gorm.transactions.ReadOnly

@ReadOnly
class ClientesController extends RestfulController<Clientes>{
    ClientesController() {super (Clientes)}

    def index() {
        respond Clientes.list().collect{
            [
                    id: it?.id,
                    titularNombre: it?.titularNombre,
                    apellidoPaterno: it?.apellidoPaterno,
                    apellidoMaterno: it?.apellidoMaterno,
                    grupoFamilia: it?.grupoFamilia.descLabel,
                    promotor: it?.promotor.descLabel,
                    tipoInversionista: it?.tipoInversionista.descLabel,
                    excentoIsr: it?.excentoIsr,
                    excentoIva: it?.excentoIva,
                    fechaNacimiento: it?.fechaNacimiento,
                    entidadFederativaNacimiento: it?.entidadFederativaNacimiento.descLabel,
                    fechaInicioOperaciones: it?.fechaInicioOperaciones,
                    estadoCivil: it?.estadoCivil,
                    profesion: it?.profesion.descLabel,
                    nombreEmpresaPrestaServicios: it?.nombreEmpresaPrestaServicios,
                    nombrePuesto: it?.nombrePuesto,
                    funcionesGeneralesDirectivas: it?.funcionesGeneralesDirectivas,
                    nivelJerarquico: it?.nivelJerarquico,
                    antiguedadEmpleo: it?.antiguedadEmpleo,
                    sectorEmpresa: it?.sectorEmpresa,
                    giroEmpresa: it?.giroEmpresa,
                    tipoIngreso: it?.tipoIngreso,
                    ingresoAdicional: it?.ingresoAdicional,
                    sectorPrestaServicio: it?.sectorPrestaServicio,
                    giroEspecificoServicios: it?.giroEspecificoServicios,
                    sectorEmpresa2: it?.sectorEmpresa2,
                    razonSocialEmpresa: it?.razonSocialEmpresa,
                    actividadEmpresa: it?.actividadEmpresa,
                    ingresoAdicional2: it?.ingresoAdicional2,
                    ocupacionActual: it?.ocupacionActual,
                    fuenteIngresos: it?.fuenteIngresos,
                    sociedadesAsociacionesRFCEmpresa: it?.sociedadesAsociacionesRFCEmpresa,
                    nacionalidadEmpresa: it?.nacionalidadEmpresa.descLabel,
                    telefonoEmpresa: it?.telefonoEmpresa,
                    sectorEmpresa3: it?.sectorEmpresa3,
                    actividadGiroEspecificoEmpresa: it?.actividadGiroEspecificoEmpresa,
                    porcentajeCapitalSocial: it?.porcentajeCapitalSocial,
                    consejeroEmpresaRFCEmpresa: it?.consejeroEmpresaRFCEmpresa,
                    nacionalidadEmpresa2: it?.nacionalidadEmpresa2.descLabel,
                    telefonoEmpresa2: it?.telefonoEmpresa2,
                    sectorEmpresa4: it?.sectorEmpresa4,
                    actividadGiroEmpresa3: it?.actividadGiroEmpresa3,
                    vinculoPatrimonial: it?.vinculoPatrimonial,
                    consejeroEmpresa: it?.consejeroEmpresa,
                    cargoDesempeno: it?.cargoDesempeno,
                    nombreInstitucion: it?.nombreInstitucion,
                    institucionCargoExtranjero: it?.institucionCargoExtranjero,
                    pais: it?.pais.descLabel,
                    cargo: it?.cargo,
                    relacionPersonaNacionalExtranjera: it?.relacionPersonaNacionalExtranjera,
                    cargo2: it?.cargo2,
                    institucionDesempenaCargo: it?.institucionDesempenaCargo,

//                    cotitular
                    nombreCotitular: it?.nombreCotitular,
                    apellidoPaternoC: it?.apellidoPaternoC,
                    apellidoMaternoC: it?.apellidoMaternoC,
                    estadoCivilC: it?.estadoCivilC,
                    lugarPrestaServicios: it?.lugarPrestaServicios,
                    nombrePuestoC: it?.nombrePuestoC,
                    funcionesGeneralesDirectivasC: it?.funcionesGeneralesDirectivasC,
                    nivelJerarquicoC: it?.nivelJerarquicoC,
                    antiguedadEmpleoC: it?.antiguedadEmpleoC,
                    sectorEmpresaC: it?.sectorEmpresaC,
                    tipoIngresoC: it?.tipoIngresoC,
                    ingresoAdicionalC: it?.ingresoAdicionalC,
                    formasProporcionaServicios: it?.formasProporcionaServicios,
                    sectorPrestaServicios: it?.sectorPrestaServicios,
                    actividadGiroEEmpresaC: it?.actividadGiroEEmpresaC,
                    rfcEmpresa: it?.rfcEmpresa,
                    sectorDEmpresaC: it?.sectorDEmpresaC,
                    actividadGiroEmpresaC: it?.actividadGiroEmpresaC,
                    cingresoAdicionalC: it?.cingresoAdicionalC,
                    ocupacionActualC: it?.ocupacionActualC,
                    fuenteIngresoC: it?.fuenteIngresoC,
                    razonSocialEmpresaC: it?.razonSocialEmpresaC,
                    rfc: it?.rfc,
                    nacionalidadEmpresaC: it?.nacionalidadEmpresaC.descLabel,
                    telefonoEmpresaC: it?.telefonoEmpresaC,
                    sectorDeEmpresaC: it?.sectorDeEmpresaC,
                    actividadDeEmpresaC: it?.actividadDeEmpresaC,
                    porcentajeEmpresaC: it?.porcentajeEmpresaC,
                    esConsejero: it?.esConsejero,
                    razonSocialC: it?.razonSocialC,
                    rfcC: it?.rfcC,
                    nacionalidadDEmpresaC: it?.nacionalidadDEmpresaC.descLabel,
                    telefonoDEmpresaC: it?.telefonoDEmpresaC,
                    sectorDLEmpresaC: it?.sectorDLEmpresaC,
                    actividadDEEmpresaC: it?.actividadDEEmpresaC,
                    porcentajeEmpresaPertenece: it?.porcentajeEmpresaPertenece,
                    consejeroEmpresaC: it?.consejeroEmpresaC,
            ]
        }
    }
}
